sudo: false
language: python
cache:
  directories:
  - $HOME/.cache/pip
install: pip install -U pip tox wheel
script: tox
notifications:
  email: false
env:
  - TOXENV=py27-django-17
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py33-django-17
  - TOXENV=py33-django-18
  - TOXENV=py34-django-17
  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
