language: python
python:
  - 2.7
  - 3.4
  - 3.3
env:
  - DJANGO=django==1.8.7
  - DJANGO=django==1.7.11
install:
  - pip install $DJANGO
  - python setup.py -q install
script: cd test_project && python manage.py test require -v 2
notifications:
  email: false
