language: python
python:
  - 2.7
  - 3.4
  - 3.3
env:
  - DJANGO=django>=1.8, <1.9
  - DJANGO=django>=1.7, <1.8
install:
  - pip install $DJANGO
  - python setup.py -q install
script: cd test_project && python manage.py test require -v 2
notifications:
  email: false
