name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run_tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version: [ 2.7,3.4,3.5,3.6 ]
        toxenv: [ django-18,django-19,django-110,django-111 ]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -U pip tox wheel

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
